// Generated by tools/generate_photo_assets.py. Do not edit by hand.

export const photoDecks = [
  {
    "id": "portraits",
    "kicker": "Portraits / people in transit",
    "title": "人物与旅途",
    "description": "从哈尔滨、纽约到开罗，人像不追求棚拍感，更像旅途中被城市光线留下的现场。",
    "tags": [
      "night portrait",
      "campus",
      "travel notes"
    ],
    "previewIndices": [
      0,
      2,
      3,
      4
    ],
    "images": [
      {
        "id": "portraits-01",
        "src": "portraits/display/%E5%93%88%E5%B0%94%E6%BB%A8%20%E9%93%81%E8%B7%AF%E6%A1%A5.jpg",
        "thumbSrc": "portraits/thumbs/%E5%93%88%E5%B0%94%E6%BB%A8%20%E9%93%81%E8%B7%AF%E6%A1%A5.jpg",
        "title": "Arc Light",
        "caption": "哈尔滨松花江边的夜色和桥拱灯带一起收进虚化里，这张更像一张城市夜行的开场照。",
        "alt": "人像照片：Arc Light",
        "location": "哈尔滨",
        "subject": "铁路桥",
        "sourceTitle": "哈尔滨 铁路桥",
        "sourceFile": "哈尔滨 铁路桥.jpg",
        "heroPosition": "center 32%",
        "dimensions": {
          "width": 8664,
          "height": 5784
        }
      },
      {
        "id": "portraits-02",
        "src": "portraits/display/%E5%93%88%E5%B0%94%E6%BB%A8%20%E9%93%81%E8%B7%AF%E6%A1%A5%20%E8%83%8C%E6%99%AF.jpg",
        "thumbSrc": "portraits/thumbs/%E5%93%88%E5%B0%94%E6%BB%A8%20%E9%93%81%E8%B7%AF%E6%A1%A5%20%E8%83%8C%E6%99%AF.jpg",
        "title": "Shoreline Back",
        "caption": "背对镜头站在江边，把人物放进远处灯光和水面的留白里。",
        "alt": "人像照片：Shoreline Back",
        "location": "哈尔滨",
        "subject": "铁路桥 背景",
        "sourceTitle": "哈尔滨 铁路桥 背景",
        "sourceFile": "哈尔滨 铁路桥 背景.jpg",
        "heroPosition": "center 32%",
        "dimensions": {
          "width": 8664,
          "height": 5784
        }
      },
      {
        "id": "portraits-03",
        "src": "portraits/display/%E5%93%A5%E5%A4%A7%20Butler.jpg",
        "thumbSrc": "portraits/thumbs/%E5%93%A5%E5%A4%A7%20Butler.jpg",
        "title": "Butler Quiet",
        "caption": "在 Butler 前留下的一帧更接近读书生活本身，安静但不空。",
        "alt": "人像照片：Butler Quiet",
        "location": "哥大",
        "subject": "Butler",
        "sourceTitle": "哥大 Butler",
        "sourceFile": "哥大 Butler.JPG",
        "heroPosition": "center 32%",
        "dimensions": {
          "width": 6000,
          "height": 3368
        }
      },
      {
        "id": "portraits-04",
        "src": "portraits/display/%E5%9F%83%E5%8F%8A%E5%BC%80%E7%BD%97%20%E9%87%91%E5%AD%97%E5%A1%94.jpg",
        "thumbSrc": "portraits/thumbs/%E5%9F%83%E5%8F%8A%E5%BC%80%E7%BD%97%20%E9%87%91%E5%AD%97%E5%A1%94.jpg",
        "title": "Desert Interval",
        "caption": "人在金字塔前变成尺度参考，旅途的开阔感比摆拍姿态更重要。",
        "alt": "人像照片：Desert Interval",
        "location": "埃及开罗",
        "subject": "金字塔",
        "sourceTitle": "埃及开罗 金字塔",
        "sourceFile": "埃及开罗 金字塔.JPG",
        "heroPosition": "center 32%",
        "dimensions": {
          "width": 6000,
          "height": 3368
        }
      },
      {
        "id": "portraits-05",
        "src": "portraits/display/%E5%BB%B6%E5%90%89%E5%A4%A7%E5%AD%A6%20%E7%BD%91%E7%BA%A2%E5%A2%99.jpg",
        "thumbSrc": "portraits/thumbs/%E5%BB%B6%E5%90%89%E5%A4%A7%E5%AD%A6%20%E7%BD%91%E7%BA%A2%E5%A2%99.jpg",
        "title": "Neon Wall",
        "caption": "夜色和招牌把校园入口变成一整面发光背景，人像落在城市节奏里。",
        "alt": "人像照片：Neon Wall",
        "location": "延吉大学",
        "subject": "网红墙",
        "sourceTitle": "延吉大学 网红墙",
        "sourceFile": "延吉大学 网红墙.jpg",
        "heroPosition": "center 32%",
        "dimensions": {
          "width": 5784,
          "height": 4627
        }
      }
    ]
  },
  {
    "id": "scenery",
    "kicker": "Scenery / trail and city",
    "title": "行旅风景册",
    "description": "这些风景来自日出、山脊、港湾、城市与动物现场，保留的是在路上的观看方式。",
    "tags": [
      "sunrise",
      "trail line",
      "city light"
    ],
    "previewIndices": [
      1,
      12,
      11,
      9
    ],
    "images": [
      {
        "id": "scenery-01",
        "src": "scenery/display/%E5%85%B0%E5%B7%9E%20%E4%B8%B9%E9%9C%9E%E5%9C%B0%E8%B2%8C.jpg",
        "thumbSrc": "scenery/thumbs/%E5%85%B0%E5%B7%9E%20%E4%B8%B9%E9%9C%9E%E5%9C%B0%E8%B2%8C.jpg",
        "title": "Red Strata",
        "caption": "层层起伏的丹霞像被时间切开的地表，颜色和纹理本身就是主角。",
        "alt": "风景照片：Red Strata",
        "location": "兰州",
        "subject": "丹霞地貌",
        "sourceTitle": "兰州 丹霞地貌",
        "sourceFile": "兰州 丹霞地貌.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-02",
        "src": "scenery/display/%E5%90%89%E6%9E%97%20%E6%97%A5%E5%87%BA.jpg",
        "thumbSrc": "scenery/thumbs/%E5%90%89%E6%9E%97%20%E6%97%A5%E5%87%BA.jpg",
        "title": "First Light",
        "caption": "日出刚越过地平线，低角度的金色把清晨压成很薄的一层光。",
        "alt": "风景照片：First Light",
        "location": "吉林",
        "subject": "日出",
        "sourceTitle": "吉林 日出",
        "sourceFile": "吉林 日出.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-03",
        "src": "scenery/display/%E5%93%88%E5%B0%94%E6%BB%A8%20%E4%B8%AD%E5%A4%AE%E5%A4%A7%E8%A1%97.jpg",
        "thumbSrc": "scenery/thumbs/%E5%93%88%E5%B0%94%E6%BB%A8%20%E4%B8%AD%E5%A4%AE%E5%A4%A7%E8%A1%97.jpg",
        "title": "Winter Avenue",
        "caption": "冬天的中央大街把建筑立面、行人和冷空气一起压进长街透视。",
        "alt": "风景照片：Winter Avenue",
        "location": "哈尔滨",
        "subject": "中央大街",
        "sourceTitle": "哈尔滨 中央大街",
        "sourceFile": "哈尔滨 中央大街.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-04",
        "src": "scenery/display/%E5%93%88%E5%B0%94%E6%BB%A8%20%E6%8A%97%E6%B4%AA%E7%BA%AA%E5%BF%B5%E5%A1%94.jpg",
        "thumbSrc": "scenery/thumbs/%E5%93%88%E5%B0%94%E6%BB%A8%20%E6%8A%97%E6%B4%AA%E7%BA%AA%E5%BF%B5%E5%A1%94.jpg",
        "title": "Monument Blue",
        "caption": "纪念塔前的蓝调时刻把城市地标拍得更安静，也更有北方冬夜的空气感。",
        "alt": "风景照片：Monument Blue",
        "location": "哈尔滨",
        "subject": "抗洪纪念塔",
        "sourceTitle": "哈尔滨 抗洪纪念塔",
        "sourceFile": "哈尔滨 抗洪纪念塔.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-05",
        "src": "scenery/display/%E5%9F%83%E5%8F%8A%E5%8D%A2%E5%85%8B%E7%B4%A2%20%E7%83%AD%E6%B0%94%E7%90%83.jpg",
        "thumbSrc": "scenery/thumbs/%E5%9F%83%E5%8F%8A%E5%8D%A2%E5%85%8B%E7%B4%A2%20%E7%83%AD%E6%B0%94%E7%90%83.jpg",
        "title": "Luxor Lift",
        "caption": "卢克索清晨的热气球慢慢升起，天空和地面的层次在这一刻刚好分开。",
        "alt": "风景照片：Luxor Lift",
        "location": "埃及卢克索",
        "subject": "热气球",
        "sourceTitle": "埃及卢克索 热气球",
        "sourceFile": "埃及卢克索 热气球.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 6000,
          "height": 3368
        }
      },
      {
        "id": "scenery-06",
        "src": "scenery/display/%E5%B7%B4%E5%BD%A6%E6%B7%96%E5%B0%94%20%E9%98%B4%E5%B1%B1%E5%B1%B1%E8%84%89.jpg",
        "thumbSrc": "scenery/thumbs/%E5%B7%B4%E5%BD%A6%E6%B7%96%E5%B0%94%20%E9%98%B4%E5%B1%B1%E5%B1%B1%E8%84%89.jpg",
        "title": "Mountain Silence",
        "caption": "阴山山脉的线条非常克制，适合把风和距离都留在画面里。",
        "alt": "风景照片：Mountain Silence",
        "location": "巴彦淖尔",
        "subject": "阴山山脉",
        "sourceTitle": "巴彦淖尔 阴山山脉",
        "sourceFile": "巴彦淖尔 阴山山脉.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-07",
        "src": "scenery/display/%E6%88%90%E9%83%BD%E7%86%8A%E7%8C%AB%E8%B0%B7%20%E5%A4%A7%E7%86%8A%E7%8C%AB.jpg",
        "thumbSrc": "scenery/thumbs/%E6%88%90%E9%83%BD%E7%86%8A%E7%8C%AB%E8%B0%B7%20%E5%A4%A7%E7%86%8A%E7%8C%AB.jpg",
        "title": "Bamboo Noon",
        "caption": "大熊猫趴在树干间的状态很松弛，画面重点是它和环境之间的呼吸感。",
        "alt": "风景照片：Bamboo Noon",
        "location": "成都熊猫谷",
        "subject": "大熊猫",
        "sourceTitle": "成都熊猫谷 大熊猫",
        "sourceFile": "成都熊猫谷 大熊猫.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-08",
        "src": "scenery/display/%E6%88%90%E9%83%BD%E7%86%8A%E7%8C%AB%E8%B0%B7%20%E5%B0%8F%E7%86%8A%E7%8C%AB.jpg",
        "thumbSrc": "scenery/thumbs/%E6%88%90%E9%83%BD%E7%86%8A%E7%8C%AB%E8%B0%B7%20%E5%B0%8F%E7%86%8A%E7%8C%AB.jpg",
        "title": "Branch Turn",
        "caption": "小熊猫转身的一瞬间更轻，也让枝叶和毛色形成了一次干净的对比。",
        "alt": "风景照片：Branch Turn",
        "location": "成都熊猫谷",
        "subject": "小熊猫",
        "sourceTitle": "成都熊猫谷 小熊猫",
        "sourceFile": "成都熊猫谷 小熊猫.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 5616,
          "height": 3744
        }
      },
      {
        "id": "scenery-09",
        "src": "scenery/display/%E7%8E%89%E9%BE%99%E9%9B%AA%E5%B1%B1%20%E5%86%B0%E5%B7%9D%E5%85%AC%E5%9B%AD.jpg",
        "thumbSrc": "scenery/thumbs/%E7%8E%89%E9%BE%99%E9%9B%AA%E5%B1%B1%20%E5%86%B0%E5%B7%9D%E5%85%AC%E5%9B%AD.jpg",
        "title": "Glacier Steps",
        "caption": "人在冰川公园的栈道上前进，雪线和人工路径一起给出尺度。",
        "alt": "风景照片：Glacier Steps",
        "location": "玉龙雪山",
        "subject": "冰川公园",
        "sourceTitle": "玉龙雪山 冰川公园",
        "sourceFile": "玉龙雪山 冰川公园.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-10",
        "src": "scenery/display/%E7%8E%89%E9%BE%99%E9%9B%AA%E5%B1%B1%20%E6%97%A5%E5%87%BA.jpg",
        "thumbSrc": "scenery/thumbs/%E7%8E%89%E9%BE%99%E9%9B%AA%E5%B1%B1%20%E6%97%A5%E5%87%BA.jpg",
        "title": "Snowline Dawn",
        "caption": "日出把雪山顶部先点亮，冷暖转换比山体本身更抓人。",
        "alt": "风景照片：Snowline Dawn",
        "location": "玉龙雪山",
        "subject": "日出",
        "sourceTitle": "玉龙雪山 日出",
        "sourceFile": "玉龙雪山 日出.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-11",
        "src": "scenery/display/%E7%94%98%E8%82%83%E7%9C%81%E5%8D%9A%20%E9%93%9C%E5%A5%94%E9%A9%AC.jpg",
        "thumbSrc": "scenery/thumbs/%E7%94%98%E8%82%83%E7%9C%81%E5%8D%9A%20%E9%93%9C%E5%A5%94%E9%A9%AC.jpg",
        "title": "Bronze Gallop",
        "caption": "展柜里的铜奔马不是纯文物照，更像一次把动势从玻璃后面重新拉出来。",
        "alt": "风景照片：Bronze Gallop",
        "location": "甘肃省博",
        "subject": "铜奔马",
        "sourceTitle": "甘肃省博 铜奔马",
        "sourceFile": "甘肃省博 铜奔马.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 4864
        }
      },
      {
        "id": "scenery-12",
        "src": "scenery/display/%E9%87%8D%E5%BA%86%20%E5%8D%95%E8%BD%A8%E5%88%97%E8%BD%A6.jpg",
        "thumbSrc": "scenery/thumbs/%E9%87%8D%E5%BA%86%20%E5%8D%95%E8%BD%A8%E5%88%97%E8%BD%A6.jpg",
        "title": "Through the Hill",
        "caption": "重庆单轨从楼宇和坡地之间穿过去，这座城市最有辨识度的节奏就在这一幕里。",
        "alt": "风景照片：Through the Hill",
        "location": "重庆",
        "subject": "单轨列车",
        "sourceTitle": "重庆 单轨列车",
        "sourceFile": "重庆 单轨列车.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 4864
        }
      },
      {
        "id": "scenery-13",
        "src": "scenery/display/%E9%A6%99%E6%B8%AF%20%E7%BB%B4%E5%A4%9A%E5%88%A9%E4%BA%9A%E6%B8%AF.jpg",
        "thumbSrc": "scenery/thumbs/%E9%A6%99%E6%B8%AF%20%E7%BB%B4%E5%A4%9A%E5%88%A9%E4%BA%9A%E6%B8%AF.jpg",
        "title": "Harbor Blue",
        "caption": "维港的天光、水面和楼群被压进同一层蓝色里，画面更像一次长呼吸。",
        "alt": "风景照片：Harbor Blue",
        "location": "香港",
        "subject": "维多利亚港",
        "sourceTitle": "香港 维多利亚港",
        "sourceFile": "香港 维多利亚港.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      },
      {
        "id": "scenery-14",
        "src": "scenery/display/%E9%A6%99%E6%B8%AF%20%E9%BE%99%E8%84%8A.jpg",
        "thumbSrc": "scenery/thumbs/%E9%A6%99%E6%B8%AF%20%E9%BE%99%E8%84%8A.jpg",
        "title": "Dragon's Spine",
        "caption": "龙脊步道最迷人的不是终点，而是海风、山脊和弯线一路把人带过去。",
        "alt": "风景照片：Dragon's Spine",
        "location": "香港",
        "subject": "龙脊",
        "sourceTitle": "香港 龙脊",
        "sourceFile": "香港 龙脊.JPG",
        "heroPosition": "center 50%",
        "dimensions": {
          "width": 8640,
          "height": 5760
        }
      }
    ]
  }
];

export const photoHighlights = {
  "portraitPrimary": {
    "deckId": "portraits",
    "index": 0
  },
  "portraitSecondary": {
    "deckId": "portraits",
    "index": 2
  },
  "sceneryPrimary": {
    "deckId": "scenery",
    "index": 1
  },
  "scenerySecondary": {
    "deckId": "scenery",
    "index": 12
  },
  "aboutPortrait": {
    "deckId": "portraits",
    "index": 0
  }
};

export const photoSummary = {
  "totalPhotos": 19,
  "deckCounts": {
    "portraits": 5,
    "scenery": 14
  }
};
